### ISSUE TITLE
Not working for bash

### ISSUE THREAD

**Issue by erikw** [benvan/sandboxd#5]
sandboxd unfortunately does not work in bash.

With the example configuration listed in README, when you start bash you get this error

```bash
$ bash
bash: eval: line 42: syntax error: unexpected end of file
bash: eval: line 42: syntax error: unexpected end of file
bash: local: can only be used in a function
bash: local: can only be used in a function
bash: eval: line 41: syntax error near unexpected token `)'
bash: eval: line 41: `(){ sandbox ;  $@ }'
```

OS: macOs `10.13.2`
Bash version:
```bash
bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin17.0.0)
```

https://github.com/benvan/sandboxd/pull/4 aims to fix this but was not finished, adding issue here so other people with the same problem can know it's a known problem!

**Comment by benvan** [comment]
This branch (tentatively) has bash support: https://github.com/benvan/sandboxd/tree/bash-support

If there are no problems I'll merge in

**Comment by erikw** [comment]
@benvan I just tested this branch, and for me it works!! :rocket:

**Comment by benvan** [comment]
Thanks @erikw - merged into master
