### ISSUE TITLE
Add a license perhaps?

### ISSUE THREAD

**Issue by jltml** [benvan/sandboxd#9]
Hi! I just started using sandboxd ≈15 minutes ago, and it's really awesome — thanks so much for almost singlehandedly solving my slow shell startup! A bit of a winding story, but: I thought of the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) repo right after that, and if you'd like, I could create a pull request to add sandboxd (since I only happened to stumble upon it through some serendipitous searching about speeding up pyenv)? If you would, however, their contributing guidelines ask that all submissions have licences (you're probably well aware, but [here's a helpful GitHub website for choosing one](https://choosealicense.com)). If you don't care, that's totally fine too! Just thought I may as well ask since this plugin is so great & more people should know about it.

**Comment by benvan** [comment]
Hey @jltml ! Thanks so much for your kind words and the suggestion :) 

I've just added a license (MIT) - please do feel free to use the project however you'd like. 

Also, if you do think the project would be a good candidate for submission to awesome-zsh-plugins, I'd be both onboard and grateful!

**Comment by jltml** [comment]
Ah, of course! Seriously, it's a wonderful plugin :)

Thanks so much — I [submitted a PR](https://github.com/unixorn/awesome-zsh-plugins/pull/1241) on the awesome-zsh-plugins repo… fingers crossed!
